apiVersion: v1
kind: Secret
metadata:
  name: ror-firewall-ssi-secrets
  namespace: ssi
type: Opaque
stringData:
  secrets.yaml: |
    ---
    NAM_TOKEN: "<your-nam-api-token-here>"
    SPLUNK_TOKEN: "<your-splunk-hec-token-here>"
