
namespace: "ssi"
nameOverride: ""
image:
  repository: "ncr.sky.nhn.no/ghcr/norskhelsenett/dcn-ror-firewall-ssi"
  tag: "latest"
  pullPolicy: "Always"

successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 3
allowConcurrent: false

schedule: "*/15 * * * *"

limits:
  memory:
    min: "384Mi"
    max: "1152Mi"
  cpu:
    min: "300m"
    max: "600m"

settings:
  infrastructure: prod # prod, qa
  environment: production # Runtime environment: development, production
  priority: low # low, medium, high
  interval: 300 # In seconds
  timeout: 3000 # In milliseconds
  continuousMode: false
  
integration:
  nam:
    url: ""
    test_int: "" # Only used for development testing
  splunk:
    url: "https://splunk-hec.nhn.no"
    index: "dc_nam"
    source: "ror-firewall-ssi:prod"

credentials:
  namToken: ""
  splunkToken: ""

workspace: ror-firewall-ssi